#### Ford Football Predictions League ####
# URL which is the source of the data
URL : 'https://www.skysports.com/'
# Seasons to extract data from
seasons : ["","2019-20"]
# Divisions to include within the scraping process
divisions : ["premier-league","championship", "league-1", "league-2"]
# Number of previous results to take into account
form: 3
# Matches to predict
game_1:
  home: "West Ham United"
  away: "Manchester City"
game_2:
  home: "Arsenal"
  away: "Leicester City"
game_3:
  home: "Aston Villa"
  away: "Leeds United"
game_4:
  home: "Brighton and Hove Albion"
  away: "West Bromwich Albion"
game_5:
  home: "Fulham"
  away: "Crystal Palace"
game_6:
  home: "Liverpool"
  away: "Sheffield United"
game_7:
  home: "Manchester United"
  away: "Chelsea"
game_8:
  home: "Southampton"
  away: "Everton"
game_9:
  home: "Wolverhampton Wanderers"
  away: "Newcastle United"
game_10:
  home: "Stoke City"
  away: "Brentford"
# Number of simulations to be run
simulations_to_run: 100000
# Top N scorelines to be produced
requested_results: 5