#### Ford Football Predictions League ####
# URL which is the source of the data
URL : 'https://www.skysports.com/'
# Seasons to extract data from
seasons : ["2020-21"]
# Divisions to include within the scraping process "premier-league","championship" "league-1", "league-2"
divisions : ["premier-league"]
# Number of previous results to take into account
form: 8
# Matches to predict
game_1:
  home: "Brighton and Hove Albion"
  away: "Wolverhampton Wanderers"
game_2:
  home: "Burnley"
  away: "Fulham"
game_3:
  home: "Chelsea"
  away: "Manchester City"
game_4:
  home: "Crystal Palace"
  away: "Sheffield United"
game_5:
  home: "Everton"
  away: "West Ham United"
game_6:
  home: "Manchester United"
  away: "Aston Villa"
game_7:
  home: "Newcastle United"
  away: "Leicester City"
game_8:
  home: "Southampton"
  away: "Liverpool"
game_9:
  home: "Tottenham Hotspur"
  away: "Leeds United"
game_10:
  home: "West Bromwich Albion"
  away: "Arsenal"
# Number of simulations to be run
simulations_to_run: 100000
# Top N scorelines to be produced
requested_results: 5