#### Ford Football Predictions League ####
# URL which is the source of the data
URL : 'https://www.skysports.com/'
# Seasons to extract data from
seasons : ["2020-21"]
# Divisions to include within the scraping process "premier-league","championship" "league-1", "league-2"
divisions : ["premier-league", "championship"]
# Number of previous results to take into account
form: 10
# Matches to predict
game_1:
  home: "Southampton"
  away: "Chelsea"
game_2:
  home: "Burnley"
  away: "West Bromwich Albion"
game_3:
  home: "Fulham"
  away: "Sheffield United"
game_4:
  home: "West Ham United"
  away: "Tottenham Hotspur"
game_5:
  home: "Wolverhampton Wanderers"
  away: "Leeds United"
game_6:
  home: "Liverpool"
  away: "Everton"
game_7:
  home: "Aston Villa"
  away: "Leicester City"
game_8:
  home: "Arsenal"
  away: "Manchester City"
game_9:
  home: "Manchester United"
  away: "Newcastle United"
game_10:
  home: "Bristol City"
  away: "Barnsley"
# Number of simulations to be run
simulations_to_run: 100000
# Top N scorelines to be produced
requested_results: 5