#### Ford Football Predictions League ####
# URL which is the source of the data
URL : 'https://www.skysports.com/'
# Seasons to extract data from
seasons : ["2020-21"]
# Divisions to include within the scraping process "premier-league","championship" "league-1", "league-2"
divisions : ["premier-league", "championship"]
# Number of previous results to take into account
form: 5
# Matches to predict
game_1:
  home: "Wolverhampton Wanderers"
  away: "West Bromwich Albion"
game_2:
  home: "Leeds United"
  away: "Brighton and Hove Albion"
game_3:
  home: "West Ham United"
  away: "Burnley"
game_4:
  home: "Aston Villa"
  away: "Everton"
game_5:
  home: "Leicester City"
  away: "Southampton"
game_6:
  home: "Sheffield United"
  away: "Tottenham Hotspur"
game_7:
  home: "Liverpool"
  away: "Manchester United"
game_8:
  home: "Manchester City"
  away: "Crystal Palace"
game_9:
  home: "Coventry City"
  away: "Sheffield Wednesday"
game_10:
  home: "Queens Park Rangers"
  away: "Wycombe Wanderers"
# Number of simulations to be run
simulations_to_run: 100000
# Top N scorelines to be produced
requested_results: 5