#### Ford Football Predictions League ####
# URL which is the source of the data
URL : 'https://www.skysports.com/'
# Seasons to extract data from
seasons : ["","2019-20"]
# Divisions to include within the scraping process
divisions : ["premier-league","championship", "league-1", "league-2"]
# Matches to predict
game_1:
  home: "Brighton and Hove Albion"
  away: "Manchester United"
game_2:
  home: "Burnley"
  away: "Southampton"
game_3:
  home: "Crystal Palace"
  away: "Everton"
game_4:
  home: "Tottenham Hotspur"
  away: "Newcastle United"
game_5:
  home: "West Ham United"
  away: "Wolverhampton Wanderers"
game_6:
  home: "West Bromwich Albion"
  away: "Chelsea"
game_7:
  home: "Sheffield United"
  away: "Leeds United"
game_8:
  home: "Fulham"
  away: "Aston Villa"
game_9:
  home: "Manchester City"
  away: "Leicester City"
game_10:
  home: "Birmingham City"
  away: "Rotherham United"
# Number of simulations to be run
simulations_to_run: 10000
requested_results: 5