#### Ford Football Predictions League ####
# URL which is the source of the data
URL : 'https://www.skysports.com/'
# Seasons to extract data from
seasons : ["2020-21"]
# Divisions to include within the scraping process "premier-league","championship" "league-1", "league-2"
divisions : ["league-2"]
# Number of previous results to take into account
form: 5
# Matches to predict
game_1:
  home: "Forest Green"
  away: "Bolton Wanderers"
game_2:
  home: "Exeter City"
  away: "Salford City"
game_3:
  home: "Colchester United"
  away: "Bradford"
game_4:
  home: "Grimsby Town"
  away: "Walsall"
game_5:
  home: "Harrogate Town"
  away: "Newcastle United"
game_6:
  home: "West Ham United"
  away: "Arsenal"
game_7:
  home: "Aston Villa"
  away: "Tottenham Hotspur"
game_8:
  home: "Barnsley"
  away: "Sheffield Wednesday"
game_9:
  home: "Norwich City"
  away: "Blackburn Rovers"
game_10:
  home: "Preston North End"
  away: "Luton Town"
# Number of simulations to be run
simulations_to_run: 100000
# Top N scorelines to be produced
requested_results: 5