#### Ford Football Predictions League ####
# URL which is the source of the data
URL : 'https://www.skysports.com/'
# Seasons to extract data from
seasons : ["2020-21"]
# Divisions to include within the scraping process "premier-league","championship" "league-1", "league-2"
divisions : ["premier-league", "championship"]
# Number of previous results to take into account
form: 5
# Matches to predict
game_1:
  home: "Leicester City"
  away: "Liverpool"
game_2:
  home: "Brighton and Hove Albion"
  away: "Aston Villa"
game_3:
  home: "Crystal Palace"
  away: "Burnley"
game_4:
  home: "Everton"
  away: "Fulham"
game_5:
  home: "Southampton"
  away: "Wolverhampton Wanderers"
game_6:
  home: "West Bromwich Albion"
  away: "Manchester United"
game_7:
  home: "West Ham United"
  away: "Sheffield United"
game_8:
  home: "Manchester City"
  away: "Tottenham Hotspur"
game_9:
  home: "Arsenal"
  away: "Leeds United"
game_10:
  home: "Birmingham City"
  away: "Luton Town"
# Number of simulations to be run
simulations_to_run: 100000
# Top N scorelines to be produced
requested_results: 5