simulations_to_run: 10000
game_1:
  home: "EVE"
  away: "WBA"
game_2:
  home: "LEE"
  away: "FUL"
game_3:
  home: "LEI"
  away: "BUR"
game_4:
  home: "MUN"
  away: "CRY"
game_5:
  home: "SOU"
  away: "TOT"
game_6:
  home: "ARS"
  away: "WHU"
game_7:
  home: "AVL"
  away: "SHU"
game_8:
  home: "NEW"
  away: "BHA"
game_9:
  home: "CHE"
  away: "LIV"
game_10:
  home: "QPR"
  away: "SHW"
