simulations_to_run: 10000
game_1:
  home: "BHA"
  away: "MUN"
game_2:
  home: "BUR"
  away: "SOU"
game_3:
  home: "CRY"
  away: "EVE"
game_4:
  home: "TOT"
  away: "NEW"
game_5:
  home: "WHU"
  away: "WOL"
game_6:
  home: "WBA"
  away: "CHE"
game_7:
  home: "SHU"
  away: "LEE"
game_8:
  home: "FUL"
  away: "AVL"
game_9:
  home: "MCI"
  away: "LEI"
game_10:
  home: "BIR"
  away: "ROT"
