#### Ford Football Predictions League ####
# URL which is the source of the data
URL : 'https://www.skysports.com/'
# Seasons to extract data from
seasons : ["2020-21"]
# Divisions to include within the scraping process "premier-league","championship" "league-1", "league-2"
divisions : ["premier-league", "championship"]
# Number of previous results to take into account
form: 5
# Matches to predict
game_1:
  home: "Bournemouth"
  away: "Southampton"
game_2:
  home: "Everton"
  away: "Manchester City"
game_3:
  home: "Chelsea"
  away: "Sheffield United"
game_4:
  home: "Leicester City"
  away: "Manchester United"
game_5:
  home: "Brighton and Hove Albion"
  away: "Newcastle United"
game_6:
  home: "West Ham United"
  away: "Arsenal"
game_7:
  home: "Aston Villa"
  away: "Tottenham Hotspur"
game_8:
  home: "Barnsley"
  away: "Sheffield Wednesday"
game_9:
  home: "Norwich City"
  away: "Blackburn Rovers"
game_10:
  home: "Preston North End"
  away: "Luton Town"
# Number of simulations to be run
simulations_to_run: 100000
# Top N scorelines to be produced
requested_results: 5