name: Premier League Predictions
on: [push]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Format code
        run: python -m black main.py

      - name: Lint with pylint
        run: python -m pylint --disable=R,C main.py

      - name: Test with pytest
        run: python -m pytest -vv

      - name: Run Snyk to check for vulnerabilities in dependencies
        uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --fail-on=all

      - name: Lint with hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Build Container
        run: docker build -t premier-league-predictions .
